# https://taskfile.dev

version: '3'

includes:
  actiniaria:
    taskfile: systems/actiniaria/Taskfile.yml
    dir: systems/actiniaria

tasks:
  default:
    - task: actiniaria:guix:home-reconfigure
